### ISSUE TITLE
Installer is broken

### ISSUE THREAD

**Issue by hhaeb** [MarcoAndreaBuchmann/bme280pi#16]
The 4 -years old installer ist broken: 
SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.

Can you please provide a working version?
Thank you

**Comment by MarcoAndreaBuchmann** [comment]
Thanks for raising this issue. The solution is to use `pip install .` instead of `python setup.py install`. I have updated the README in https://github.com/MarcoAndreaBuchmann/bme280pi/pull/17 - please have a look and let me know if it works for you.

**Comment by hhaeb** [comment]
OK - works -Thank you!
