### ISSUE TITLE
Make I2C address configurable

### ISSUE THREAD

**Issue by WO15** [MarcoAndreaBuchmann/bme280pi#8]
Currently you use self.device_id = 0x76 as I2C address. This is indeed the default address of the BME280 sensor however you can configure the sensor so the I2C address is 0x77. Normally this is done by soldering a "jumper" on the PCB. Solder pads for such a jumper are visible just above BME280 text on printed circuit board in https://www.raspberrypi-spy.co.uk/2016/07/using-bme280-i2c-temperature-pressure-sensor-in-python/
This can be useful if you want to use 2 BME280 sensors on one Raspberry, e.g. to compare/calibrate values or measure e.g. 2 times the pressure/temp/humidity inside and outside.
would be great if you can specify in the user code e.g. 
sensor_address = 0x76
sensor_address = 0x77
If not specified you can use sensor_address = 0x76 to prevent existing code to break.
P.s. additionally some sensor boards are configured with address 0x77 out of the box (these will not work with the current code)

**Comment by MarcoAndreaBuchmann** [comment]
Thank you @WO15 for opening this issue. I think this could be a new optional argument in the `Sensor` class when initializing (I'm happy to implement that). Would that be a good solution in your view?

**Comment by MarcoAndreaBuchmann** [comment]
Hi @WO15 ,

I've implemented an optional argument called `address` in `Sensor` that allows the user to specify the sensor's address. Please give it a test drive:

```
git clone https://github.com/MarcoAndreaBuchmann/bme280pi.git
git checkout feat/sensor_address
cd bme280pi
python setup.py install
```

and in your script, you should then be able to initialize two different sensors:

```
from bme280pi import Sensor

sensor1 = Sensor(address=0x76)
sensor2 = Sensor(address=0x77)

print(sensor1.get_data())
print(sensor2.get_data())
```

Please report back if this works as you had imagined and thanks again for having reported this issue!

**Comment by WO15** [comment]
Looks good, however do not know how to load a separate branch to my raspberry and run the code. So can not test it.
One remarks, probably wise to use the default I2C address as currently used in the master branch if no address is indicated ergo sensorx = Sensor() will use address=0x76. To prevent that existing code breaks.

**Comment by WO15** [comment]
Did made the change manually on my local files in /home/pi/.local/lib/python3.7/site-packages/bme280pi/sensor.py when I change it from 0x76  to 0x77 and back I toggle between the 2 sensors. So the existing code does support this change without issues. Having the option would make it "manageble"

**Comment by MarcoAndreaBuchmann** [comment]
I've merged a pull request that contains all the code necessary. Please update your local package (e.g. `pip install -U bme280pi`) and see if this new version works for you. You should be able to initialize the sensor with `sensor1 = Sensor(address=0x76)` and a second sensor with `sensor2 = Sensor(address=0x77)`. If no address is specified, it will go back to the default one (0x76).

Please report back if this works for you. Thanks!

**Comment by WO15** [comment]
Did update the module with pip, and ran the code below.

sensor0 = Sensor()
sensor1 = Sensor(address=0x76)
sensor2 = Sensor(address=0x77)

print (sensor0.get_data())
print (sensor1.get_data())
print (sensor2.get_data())

It works as expected, thank you a lot for your very quick response.

**Comment by WO15** [comment]
works well tested for a day no issues.

**Comment by MarcoAndreaBuchmann** [comment]
Thanks @WO15 for checking the new version. I'm glad to hear that it now works for your purposes, and please feel free to open another issue if you come across anything else :smile:
